sonar.projectKey=kadupulhq_website
sonar.organization=kadupulhq
sonar.sources=src,scripts,astro.config.mjs
sonar.tests=scripts/__tests__
sonar.exclusions=**/__tests__/**,**/*.png
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
