name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  release:
    uses: kadupulhq/.github/.github/workflows/release.yml@0bd907f8a3b77376b0cd79eaf111233defab41cf
    permissions:
      contents: write
