name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  release:
    uses: kadupulhq/.github/.github/workflows/release.yml@fa9a77df6be6cd5e301b8004e52e63acf91cabdc
    permissions:
      contents: write
