name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  release:
    uses: kadupulhq/.github/.github/workflows/release.yml@5493a087143bf3971ec57fee53138d24d538824b
    permissions:
      contents: write
